export default Types = {
    ERROSOLICITACAO : '/errosolicitacao',
    SETSOLICITACAO : 'SETSOLICITACOES',
    SETSOLICITACAOACEITA : '/SETSOLICITACAOACEITA',
    COUNTPENDENTES : '/COUNTPENDENTES',
    COUNTACEITAS : '/COUNTACEITAS'
}