export default Types = {
    FINDMYPOSTS : 'FINDMYPOSTS',
    REMOVEMYPOSTS : "REMOVEMYPOSTS",
    EDITMYPOSTS : "EDITMYPOSTS",
    ADDNOVASIMAGENS : '/ADDNOVASIMAGENS',
    NOVAFOTO : '/NOVAFOTO',
    REMOVENOVAFOTO : '/REMOVENOVAFOTO',
    SETENDERECO : '/SETENDERECO',
    SETCEPCONFIG :'/SETCEPCONFIG'
}